In [2]:
import numpy as np
arr1=np.array([1,2,3]) #1D ARRAY
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]]) #2D ARRAY
print(arr2)

#Checking type and shape
print("Type:",type(arr1),"and",type(arr2))
print("Shape:",arr1.shape,"and",arr2.shape)


[1 2 3]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'> and <class 'numpy.ndarray'>
Shape: (3,) and (2, 3)


In [3]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data,dtype=np.int32)

print("Python list size:", sys.getsizeof(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056 bytes
NumPy array size: 4000 bytes
