In [1]:
import numpy as np 
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,1]])
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11  1]]


In [13]:
print(np.zeros((1,2)))

[[0. 0.]]


In [16]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [4]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [5]:
np.arange(0,81,8)

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
#checking 
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)

(4, 3)
int64
2
12


In [8]:
#converting datatype and giving it to differnt array
print(arr1.dtype)
arr2=arr1.astype(float)
print(arr2.dtype)

int64
float64


In [9]:
#reshaping and flattening 
arr3 =arr1.reshape((2,6))
print(arr3)

arr4=arr1.flatten()
print(arr4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  1]]
[ 1  2  3  4  5  6  7  8  9 10 11  1]
