In [13]:
import numpy as np
#2D array
arr=np.array([[1,2,3],
               [4,5,6],
                [7,8,9]])
print(np.sum(arr,axis=0))#rows are added
print(np.sum(arr,axis=1))#columna are added
#3D array
arr3D=np.array([[
    [1,2,3],
    [1,2,3]
               ],[
    [3,4,5],
    [3,4,5]
               ]])
print(arr3D)
print(arr3D.ndim)


[12 15 18]
[ 6 15 24]
[[[1 2 3]
  [1 2 3]]

 [[3 4 5]
  [3 4 5]]]
3


In [22]:
print(arr3D[:,0,:])
print(arr[0:2,1:])

[[1 2 3]
 [3 4 5]]
[[2 3]
 [5 6]]


In [36]:
strARR=np.array(['string','is','made','using','numpy_array'])#You can also set (dtype=str) for string
print(strARR.dtype)

<U11
