In [1]:
import numpy as np
arr1=np.array([[1,2,3],[8,9,7],[12,19,4]])
print("shape",arr1.shape)

shape (3, 3)


In [2]:
arrINT=np.array([1.1,2.2,3.3])
print(arrINT.dtype)

float64


In [3]:
arrFLOAT=arrINT.astype(int)
print(arrFLOAT.dtype)
print(arrFLOAT)

int64
[1 2 3]


In [4]:
arr2=np.arange(1,7,1)
print(arr2)
print(arr2[[1,3,5]])#fancy indexing 

[1 2 3 4 5 6]
[2 4 6]


In [5]:
arr3=np.ones((1,9))
print(arr3)
arr4=arr3.reshape((3,3))
print(arr4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr5=np.array([20,200,300,80,10,40,50])
print(arr5[[1,3,6]])
print(arr5[arr5>50])

[200  80  50]
[200 300  80]
