In [30]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape: ",arr1.shape)

Shape:  (3, 3)


In [31]:
arr2=np.array([1.1,2.2,3.3])
print(arr2,arr2.dtype)
arr3=arr2.astype(int)
print(arr3,arr3.dtype)


[1.1 2.2 3.3] float64
[1 2 3] int64


In [42]:
arr4=np.array([1,10,3,4,5,6,7,8,9])
print(arr4[arr4%2==0])

[10  4  6  8]


In [43]:
arr5=arr4.reshape(3,3)
print(arr5)

[[ 1 10  3]
 [ 4  5  6]
 [ 7  8  9]]


In [44]:
arr2+10

array([11.1, 12.2, 13.3])

In [45]:
print(np.diff(arr4))

[ 9 -7  1  1  1  1  1  1]
